version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234Joeking92$%
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: josephemekaonah/user_management:latest
    container_name: user_management
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL:-jdbc:postgresql://postgres:5432/devops_db}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234Joeking92$%
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: